# Generated by Django 5.1 on 2024-09-02 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='applied_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
